### ISSUE TITLE
Possible to swap an individual item's bank menu entries separately from its non-bank menu entries?

### ISSUE THREAD

**Issue by Anonymous75** [geheur/More-menu-entry-swaps#14]
Let's say I have an "Open coal bag" in my inventory. 
I want the left-click option to be "Fill" while I have a bank interface open. 
When I close the bank interface, I want the left-click option to be "Empty".
I only want this swap to affect my "Open coal bag", without changing menu entries of other similar items (Gem bag, etc.).

Is this possible with the plugin? I'm having a little trouble understanding the "instructions" section.

Edit: So I somehow got it to work with these 2 lines of text:

fill,open coal bag
empty,open coal bag

Not sure how that works but I am now able to left-click Fill inside a bank, and Empty outside the bank.

**Comment by LaPenna** [comment]
Those lines work because when the bank is open, there is no "empty" option in the menu **if the bag is empty** so your "fill,open coal bag" is working.

The reason it works outside the bank despite both the "fill" and "empty" options being present - no matter if it's empty or not - is because the order you've written them. The plugin does the work of making "fill" the top option, then does the work again of making "empty" the top option.

---

The plugin **can** do this though which might help with other items that aren't fortunately missing menu options in one interface but not another.

Because the default top option when the bank is open is "deposit-1" we can make use of the following from the instructions:

"option,target,topOption,topTarget"

So the swap only occurs if the given "topOption" *would have been* at the top without any swaps.

In your case that would be:

"empty,open coal bag,deposit*,open coal bag"

I used a wildcard (*) there in cases where the default bank deposit setting is set to something like "deposit-all" or "desposit-10".

**Comment by Anonymous75** [comment]
Thanks for clarifying. I don't have much experience with coding so that's why I was confused. I've been using this plugin forever, glad to see that it's still relevant.
